name: "Run tests"
on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Lint
        run: npm run lint

  release1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Run tests
        run: npm run test-release1

  release2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Run tests
        run: npm run test-release2